# Generated by Django 3.0.7 on 2022-02-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=200, null=True)),
                ('ToDo', models.CharField(max_length=200, null=True)),
                ('Status', models.CharField(choices=[('Complete', 'Complete'), ('Not Compelete', 'Not Compelete')], max_length=200, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
