# Generated by Django 3.0.7 on 2022-02-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
