# Generated by Django 3.0.7 on 2022-02-09 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20220209_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='User',
        ),
        migrations.AddField(
            model_name='todo',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
